[workspace]
members = [
    "four-q-rs",
    "qubic-rs",
    "qubic-rpc",
    "vanity-id-generator",
    "examples/*"
]
resolver = "2"

[profile.dev]
overflow-checks = false

[profile.release]
strip = true
