[workspace]
members = [
    "four-q-rs",
    "kangarootwelve64to32",
    "qubic-web3-rs",
    "qubic-types",
    "qubic-tcp-types",
    "qubic-rpc-types",
    "qubic-rpc",
    "vanity-id-generator",
    "qubic-computor-rs",
]

[profile.dev]
overflow-checks = false

[profile.release]
strip = true