[workspace]
members = [
    "four-q-rs",
    "qubic-web3-rs",
    "qubic-types",
    "qubic-tcp-types",
    "qubic-rpc-types",
    "qubic-rpc",
    "vanity-id-generator",
    "qubic-spectrum"
]

[profile.dev]
overflow-checks = false

[profile.release]
strip = true
