[package]
name = "example-tick"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
qubic-rs = { path = "../../qubic-rs", features = ["async"] }
tokio = "1.43.0"

[[bin]]
name = "tick"
path = "main.rs"
