[package]
name = "qubic-types"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "*"
four-q = { path = "../four-q" }
kangarootwelve = "0.1.2"
hex = "*"

[profile.dev.package.compiler_builtins]
overflow-checks = false